name: Codex Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["Codex Auto Merge"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: ""
          MERGE_COMMIT_MESSAGE: "merge automatically after checks passed"
          MERGE_RETRIES: 5
          MERGE_RETRY_SLEEP: 10000

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
