name: Codex Auto PR Merge

on:
  pull_request:
    branches: [han/validation]         # 只在合到 han/validation 的 PR 上运行
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # 只处理来自同仓库（非 fork）的 PR；并且默认不处理 draft PR
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: 'Auto-approve by workflow'

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN:           ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD:           squash
          MERGE_LABELS:           ""       # 不要求必须打某个 label
          MERGE_DELETE_BRANCH:    true     # 合并后删掉来源分支
          MERGE_RETRIES:          5
          MERGE_RETRY_SLEEP:      10000
