name: r-ci

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run-r:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      # 用带缓存的依赖安装（有 renv.lock 会自动识别）
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          use-public-rspm: true
          cache-version: 1
          extra-packages: |
            any::rmarkdown
            any::knitr
            any::VGAM

      # ✅ 仅这一行是关键改动：不再用 here-doc，直接跑脚本
      - name: Run .R and render .Rmd
        run: Rscript ci/r_ci.R

      - name: Upload rendered HTMLs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: r-outputs
          path: |
            **/*.html
            **/*.nb.html
